### ISSUE TITLE
TypeError: 'DictView' object does not support item assignment

### ISSUE THREAD

**Issue by andy-maier** [zhmcclient/zhmccli#184]
From Slack channel https://ibm-systems-z.slack.com/archives/C3D97UL8N/p1623805871011700

I have encountered an error while using zhmc to obtain cpc status. This command works on the previous version, which is zhmc version 0.22.0.dev1 and zhmcclient version 0.31.0.dev1, and not on the most recent version of zhmcclient, which is version 0.31.0.
```
nuoyaxie@Nuoyas-MacBook-Pro:/ssc_devel/zrobot/zRobot_SSCVERIF/tests$ zhmc -o simple -n -h 9.152.150.166 -u woooooo -p lalalalala cpc show P0000T96 | grep -i iml
Traceback (most recent call last):
  File "/usr/local/bin/zhmc", line 10, in <module>
    sys.exit(cli())
  File "/home/nuoyaxie/.local/lib/python2.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/nuoyaxie/.local/lib/python2.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/nuoyaxie/.local/lib/python2.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/nuoyaxie/.local/lib/python2.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/nuoyaxie/.local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/nuoyaxie/.local/lib/python2.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/nuoyaxie/.local/lib/python2.7/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/nuoyaxie/.local/lib/python2.7/site-packages/zhmccli/_cmd_cpc.py", line 99, in cpc_show
    cmd_ctx.execute_cmd(lambda: cmd_cpc_show(cmd_ctx, cpc, options))
  File "/home/nuoyaxie/.local/lib/python2.7/site-packages/zhmccli/_helper.py", line 317, in execute_cmd
    cmd()
  File "/home/nuoyaxie/.local/lib/python2.7/site-packages/zhmccli/_cmd_cpc.py", line 99, in <lambda>
    cmd_ctx.execute_cmd(lambda: cmd_cpc_show(cmd_ctx, cpc, options))
  File "/home/nuoyaxie/.local/lib/python2.7/site-packages/zhmccli/_cmd_cpc.py", line 251, in cmd_cpc_show
    hide_property(properties, 'available-features-list')
  File "/home/nuoyaxie/.local/lib/python2.7/site-packages/zhmccli/_helper.py", line 979, in hide_property
    properties[prop_name] = "... (hidden)"
TypeError: 'DictView' object does not support item assignment
```

**Comment by andy-maier** [comment]
I was able to reproduce the issue, and I verified that the fix solves the issue.
The fix is in PR #187 and will be rolled back to 0.21.x.
