### ISSUE TITLE
scsi-dump cannot be performed because of unexpected secure_boot parameter

### ISSUE THREAD

**Issue by nxie13** [zhmcclient/zhmccli#280]
### Actual behavior
When I inputted a command to execute scsi-dump command:
```
nuoyaxie@Nuoyas-MacBook-Pro:/ssc_devel/zrobot/zRobot_SSCVERIF/tests$ zhmc -o simple -n -h <hmc_ip> -u <user>
-p <pw> lpar scsi-dump --force --allow-status-exceptions A96 <lpar> <device> <wwpn> <lun>

Traceback (most recent call last):
  File "/usr/local/bin/zhmc", line 11, in <module>
    load_entry_point('zhmccli==1.2.0.dev1', 'console_scripts', 'zhmc')()
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/zhmccli/_cmd_lpar.py", line 418, in lpar_scsi_dump
    cmd_ctx.execute_cmd(lambda: cmd_lpar_scsi_dump(cmd_ctx, cpc, lpar,
  File "/usr/local/lib/python3.6/dist-packages/zhmccli/_helper.py", line 318, in execute_cmd
    cmd()
  File "/usr/local/lib/python3.6/dist-packages/zhmccli/_cmd_lpar.py", line 420, in <lambda>
    options))
  File "/usr/local/lib/python3.6/dist-packages/zhmccli/_cmd_lpar.py", line 671, in cmd_lpar_scsi_dump
    **options)
  File "/home/nuoyaxie/.local/lib/python3.6/site-packages/decorator.py", line 231, in fun
    args, kw = fix(args, kw, sig)
  File "/home/nuoyaxie/.local/lib/python3.6/site-packages/decorator.py", line 203, in fix
    ba = sig.bind(*args, **kwargs)
  File "/usr/lib/python3.6/inspect.py", line 2997, in bind
    return args[0]._bind(args[1:], kwargs)
  File "/usr/lib/python3.6/inspect.py", line 2988, in _bind
    arg=next(iter(kwargs))))
TypeError: got an unexpected keyword argument 'secure_boot'
```

Even though I did not define a secure_boot option in my zhmc command.

### Expected behavior
The scsi-dump command should go through with no problem.

### Execution environment

* zhmccli version: 1.2.0.dev1
* zhmcclient version: 1.2.0
* Operating system (type+version): Ubuntu 18.04.6 LTS docker container within Macbook Pro
* HMC version: 2.16.0
* CPC version: Artemis, Classic Machine

**Comment by andy-maier** [comment]
That is clearly a bug: The `secure_boot` parameter is missing from `zhmcclient.Lpar.scsi_load()` and from `zhmcclient.Lpar.psw_restart()`.

The use of this parameter was introduced in zhmccli with PR #212, but I could not identify a corresponding PR in zhmcclient. That was bad management on our end when adding this function, and it shows one more time that we ought to be spending more time in automated tests.

**Comment by andy-maier** [comment]
This bug needs to be fixed in zhmcclient, and I created https://github.com/zhmcclient/python-zhmcclient/issues/945 for that. We will keep this issue open until we know what version of zhmcclient to require.

**Comment by andy-maier** [comment]
The fix has been rolled back into a new version zhmcclient 1.2.1, so the upcoming zhmccli package 1.2.0 will require zhmcclient 1.2.1. On the zhmccli side, no further rollback is possible.

**Comment by andy-maier** [comment]
zhmccli 1.2.0 was released today and contains the fix.
