### ISSUE TITLE
Version issue with readline package on MacOS

### ISSUE THREAD

**Issue by andy-maier** [zhmcclient/zhmccli#47]
### Actual behavior

Since today, the `zhmc` command on my MacOS fails as follows:

```
 (zhmc27) Andreass-MacBook-Pro-2:zhmccli maiera$ zhmc --version
Traceback (most recent call last):
  File "/Users/maiera/virtualenvs/zhmc27/bin/zhmc", line 6, in <module>
    from zhmccli.zhmccli import cli
  File "/Users/maiera/Projects/zhmcclient/repos/zhmccli/zhmccli/__init__.py", line 17, in <module>
    from ._cmd_info import *       # noqa: F401
  File "/Users/maiera/Projects/zhmcclient/repos/zhmccli/zhmccli/_cmd_info.py", line 20, in <module>
    from .zhmccli import cli
  File "/Users/maiera/Projects/zhmcclient/repos/zhmccli/zhmccli/zhmccli.py", line 29, in <module>
    from ._helper import CmdContext, GENERAL_OPTIONS_METAVAR, REPL_HISTORY_FILE, \
  File "/Users/maiera/Projects/zhmcclient/repos/zhmccli/zhmccli/_helper.py", line 32, in <module>
    import pyreadline as readline  # noqa: F401
```

### Analysis

Looking at the code, the `pyreadline` package is supposed to be used only on Windows, and that part of the code was reached because the `readline` package failed to import.

Importing the `readline` package fails as follows:

```
ImportError: No module named pyreadline
(zhmc27) Andreass-MacBook-Pro-2:zhmccli maiera$ python -c "import readline"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: dlopen(/Users/maiera/virtualenvs/zhmc27/lib/python2.7/lib-dynload/readline.so, 2): Library not loaded: /usr/local/opt/readline/lib/libreadline.7.dylib
  Referenced from: /Users/maiera/virtualenvs/zhmc27/lib/python2.7/lib-dynload/readline.so
  Reason: image not found
```

On my system, this directory contains version 8 of the readline DLL, but not version 7 that is expected by the Python `readline` package:

```
(zhmc27) Andreass-MacBook-Pro-2:zhmccli maiera$ ls -l /usr/local/opt/readline/lib/
-r--r--r--   1 maiera  staff   40396 Feb 11 14:18 libhistory.8.0.dylib
lrwxr-xr-x   1 maiera  staff      20 Dec 19 22:07 libhistory.8.dylib -> libhistory.8.0.dylib
-r--r--r--   1 maiera  staff   45880 Dec 19 22:07 libhistory.a
lrwxr-xr-x   1 maiera  staff      20 Dec 19 22:07 libhistory.dylib -> libhistory.8.0.dylib
-rw-r--r--   1 maiera  staff  239252 Feb 11 14:18 libreadline.8.0.dylib
lrwxr-xr-x   1 maiera  staff      21 Dec 19 22:07 libreadline.8.dylib -> libreadline.8.0.dylib
-r--r--r--   1 maiera  staff  405848 Dec 19 22:07 libreadline.a
lrwxr-xr-x   1 maiera  staff      21 Dec 19 22:07 libreadline.dylib -> libreadline.8.0.dylib
drwxr-xr-x   3 maiera  staff      96 Feb 11 14:18 pkgconfig
```

Homebrew knows that it has a version 8 of its `readline` package installed, but does not know about a version 7.

It is not clear what caused this to fail, but presumably something changed in the system that caused this.

### Execution environment

* zhmccli version: master
* zhmcclient version: 0.22.0
* Operating system (type+version): MacOS High Sierra
* HMC version: 2.14.0 (but it fails already with `zhmc --version`)
* CPC version: 2.14.0

**Comment by andy-maier** [comment]
Mitigated by PR #48.

**Comment by andy-maier** [comment]
Abandoned the approach in the original #48 (to use gnureadline instead of readline) because that takes away the history support on the arrow keys in the interactive Python shell.

The way to re-establish consistency between the OS-level readline package and Python is described in this StackOverflow answer: https://stackoverflow.com/a/40229934/1424462

That makes the use of the gnureadline package unnecessary. However, I think it is still useful to adjust the way the decision is made which package to use in zhmccli/_helper.py to the platform check based way that is used in requirements.txt. Will adjust PR #48 to do that.
