### ISSUE TITLE
zhmc lpar console crashes on exit

### ISSUE THREAD

**Issue by mwilck** [zhmcclient/zhmccli#676]
`zhmc lpar console` always crashes on exit, no matter whether I use `ctrl-c`, `ctrl-d`, or `:exit`.

```
Welcome to SUSE Linux Enterprise Server 15 SP6  (s390x) - Kernel 6.4.0-150600.21-default (sclp_line0).
linux-rdw5 login: ^C

Traceback (most recent call last):
  File "/mnt/git/tmp/1233589/venv/bin/zhmc", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/mnt/git/tmp/1233589/venv/lib64/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/git/tmp/1233589/venv/lib64/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/mnt/git/tmp/1233589/venv/lib64/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/git/tmp/1233589/venv/lib64/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/git/tmp/1233589/venv/lib64/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/git/tmp/1233589/venv/lib64/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/git/tmp/1233589/venv/lib64/python3.11/site-packages/click/decorators.py", line 45, in new_func
    return f(get_current_context().obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/git/tmp/1233589/venv/lib64/python3.11/site-packages/zhmccli/_cmd_lpar.py", line 573, in lpar_console
    cmd_ctx.execute_cmd(lambda: cmd_lpar_console(cmd_ctx, cpc, lpar, options))
  File "/mnt/git/tmp/1233589/venv/lib64/python3.11/site-packages/zhmccli/_helper.py", line 389, in execute_cmd
    cmd()  # The zhmc command function call.
    ^^^^^
  File "/mnt/git/tmp/1233589/venv/lib64/python3.11/site-packages/zhmccli/_cmd_lpar.py", line 573, in <lambda>
    cmd_ctx.execute_cmd(lambda: cmd_lpar_console(cmd_ctx, cpc, lpar, options))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/git/tmp/1233589/venv/lib64/python3.11/site-packages/zhmccli/_cmd_lpar.py", line 1130, in cmd_lpar_console
    part_console(cmd_ctx.session, lpar, refresh, logger)
  File "/mnt/git/tmp/1233589/venv/lib64/python3.11/site-packages/zhmccli/_helper.py", line 1310, in part_console
    msg_thread.join()
  File "/mnt/git/tmp/1233589/venv/lib64/python3.11/site-packages/zhmccli/_helper.py", line 1147, in join
    raise self.exc_info.value
          ^^^^^^^^^^^^^^^^^^^
```

**Expected behavior**

Does not crash

**To Reproduce**

```
~> zhmc -h $ZHMC -n lpar console --refresh $CPC $LPAR
Connected to operating system console for LPAR xyz
Enter ':exit' or press <CTRL-C> or <CTRL-D> to exit.
:exit
```

**Environment information**
* Output of `zhmc --version`:
```
~> zhmc --version
zhmc, version 1.12.0
zhmcclient, version 1.18.2
```

* HMC version:

```
~> zhmc -h zhmc2.suse.de -n console show
+--------------------+--------------------------------------+
| Field Name         | Value                                |
|--------------------+--------------------------------------|
| class              | console                              |
| description        | Suse z15                             |
| ec-mcl-description | ... (hidden)                         |
| is-locked          | False                                |
| machine-info       | machine-model   TW3                  |
|                    | machine-serial  DK16035              |
|                    | machine-type    2461                 |
| name               | HMC2z15                              |
| network-info       | ... (hidden)                         |
| object-id          | 3ff7d1e8-b2f7-3098-997c-3f21fdad6ba7 |
| object-uri         | /api/console                         |
| parent             |                                      |
| sna-name           | ZZZZZZZZ.HMC2Z15                     |
| version            | 2.15.0                               |
+--------------------+--------------------------------------+
```

**Command output**

See above

**Comment by andy-maier** [comment]
@mwilck Version 1.12.1 with the fix was released to Pypi.
